name: "26"

seed: 11
data_path: "/Users/yaroslav.hnykov/Desktop/Study/VCS/YandexCUP2023/ML/RecSys/input_data/"
n_splits: 3

batch_size: 70
max_len: 128

model: model.net.TransNetwork16
model_params: {
    input_dim: 768,
    hidden_dim: 512,
    cnn_activation: "relu"
}


criterion: training.criterion.AsymmetricLoss
criterion_params: {
    gamma_neg: 8.0
}

optimizer: training.optimizer.Adam
lr: 0.000015
lr_alpha: 30
optimizer_params: {}

scheduler: training.scheduler.Scheduler
scheduler_params: {
  num_training_steps: 9000,
  scheduler_name: "get_cosine_with_hard_restarts_schedule_with_warmup"
}

use_cv: true
cv_n_epochs: 30
cv_min_score_to_save_predictions: 0.25

use_solo: true
solo_n_epochs: 25
solo_save_last_n_epochs: 3

dataset: data.dataset.KnnTaggingDataset
collator: data.dataset.KnnCollatorWithAug
augmentations: {
  AddInversions: {
    proba: 0.05,
    p: 0.1,
  },
  AddNoise: {
    proba: 0.03,
    noise: 0.02
  },
  MixUp: {
    proba: 0.03
  }
}
knn_data: true