name: "43"

seed: 11
data_path: "/home/jupyter/mnt/s3/rnd-shared/projects/yandex_cup_2023/ML/RecSys/input_data/"
n_splits: 3

batch_size: 70
max_len: 128

model: model.net.TransNetwork17
model_params: {
    channels: [[768, 1200], [1200, 1536], [1536, 1200], [1200, 768]],
    hidden_dim: 768,
    cnn_activation: "relu",
    cnn_dropout: 0.05
}


criterion: training.criterion.AsymmetricLoss
criterion_params: {
    gamma_neg: 8.0,
    clip: 0.0,
}

optimizer: training.optimizer.Adam
lr: 0.000015
lr_alpha: 30
optimizer_params: {}

scheduler: training.scheduler.Scheduler
scheduler_params: {
  num_training_steps: 12000,
  scheduler_name: "get_cosine_with_hard_restarts_schedule_with_warmup"
}

use_cv: true
cv_n_epochs: 30
cv_min_score_to_save_predictions: 0.25

use_solo: true
solo_n_epochs: 20
solo_save_last_n_epochs: 3

dataset: data.dataset.WOTaggingDataset
dataset_between_limitations: [2, 8]
collator: data.dataset.CollatorWithAug
augmentations: {
  AddInversions: {
    proba: 0.5,
    p: 0.1,
  },
  AddNoise: {
    proba: 0.03,
    noise: 0.02
  },
  MixUp: {
    proba: 0.01
  },
  TrueMixUp: {
    proba: 1.0,
    alpha: 0.5,
    mixups_per_batch: 5
  }
}

use_ema: true
ema_decay: 0.995