name: "53"

seed: 14
data_path: "/home/jupyter/mnt/s3/rnd-shared/projects/yandex_cup_2023/ML/RecSys/input_data/"
n_splits: 3

batch_size: 64
max_len: 128

model: model.net.TransNetwork3
model_params: {
    input_dim: 768,
    hidden_dim: 512,
    encoder_cfg: {
        vocab_size: 1,
        hidden_size: 768,
        num_hidden_layers: 6,
        num_attention_heads: 6,
        intermediate_size: 3072,
        hidden_act: "gelu",
        hidden_dropout_prob: 0.001,
        attention_probs_dropout_prob: 0.001,
        max_position_embeddings: 128,
        type_vocab_size: 0,
        initializer_range: 0.02,
        layer_norm_eps: 0.0000001,
        relative_attention: false,
        max_relative_positions: -1,
        pad_token_id: 0,
        position_biased_input: true,
        pos_att_type: null,
    }
}


criterion: training.criterion.BCEWithLogitsLoss

optimizer: training.optimizer.AdamW
lr: 0.00001
lr_alpha: 20
optimizer_params: {}

scheduler: training.scheduler.Scheduler
scheduler_params: {
  num_training_steps: 10000,
  scheduler_name: "get_cosine_with_hard_restarts_schedule_with_warmup"
}
use_cv: true
cv_n_epochs: 22
cv_min_score_to_save_predictions: 0.245

use_solo: true
solo_n_epochs: 20
solo_save_last_n_epochs: 3

dataset: data.dataset.WOTaggingDataset
dataset_between_limitations: [2, 10]
collator: data.dataset.CollatorWithAug
augmentations: {
  AddInversions: {
    proba: 0.5,
    p: 0.1,
  },
  AddNoise: {
    proba: 0.03,
    noise: 0.02
  },
  MixUp: {
    proba: 0.01
  },
  TrueMixUp: {
    proba: 1.0,
    alpha: 0.5,
    mixups_per_batch: 5
  }
}

use_ema: true
ema_decay: 0.99

distillation: true