name: "55"

seed: 881
data_path: "/home/jupyter/mnt/s3/rnd-shared/projects/yandex_cup_2023/ML/RecSys/input_data/"
n_splits: 3

batch_size: 70
max_len: 64

model: model.net.TransNetwork25
model_params: {
    gru_params: {
      input_dim: 768,
      hidden_dim: 512
    }
}


criterion: training.criterion.AsymmetricLoss
criterion_params: {
    gamma_neg: 8.0,
    clip: 0.0,
}

optimizer: training.optimizer.Adam
lr: 0.000015
lr_alpha: 30
optimizer_params: {}

scheduler: training.scheduler.Scheduler
scheduler_params: {
  num_training_steps: 12000,
  scheduler_name: "get_cosine_with_hard_restarts_schedule_with_warmup"
}

use_cv: true
cv_n_epochs: 22
cv_min_score_to_save_predictions: 0.22

use_solo: true
solo_n_epochs: 20
solo_save_last_n_epochs: 3

dataset: data.dataset.WOTaggingDataset
dataset_between_limitations: [2, 8]
collator: data.dataset.CollatorWithAug
augmentations: {
  AddInversions: {
    proba: 0.3,
    p: 0.1,
  },
  AddNoise: {
    proba: 0.06,
    noise: 0.02
  },
  MixUp: {
    proba: 0.02
  },
  TrueMixUp: {
    proba: 1.0,
    alpha: 0.5,
    mixups_per_batch: 2
  }
}

use_ema: true
ema_decay: 0.995

distillation: true
