name: "5"

seed: 11
data_path: "/home/jupyter/mnt/s3/rnd-shared/projects/yandex_cup_2023/ML/RecSys/input_data/"
n_splits: 3

batch_size: 64
max_len: 100

model: model.net.TransNetwork4
model_params: {
    input_dim: 768,
    hidden_dim: 512,
    encoder_cfg: {
        vocab_size: 1,
        hidden_size: 768,
        num_hidden_layers: 12,
        num_attention_heads: 12,
        intermediate_size: 3072,
        hidden_act: "gelu",
        hidden_dropout_prob: 0.001,
        attention_probs_dropout_prob: 0.001,
        max_position_embeddings: 100,
        type_vocab_size: 0,
        initializer_range: 0.02,
        layer_norm_eps: 0.0000001,
        relative_attention: false,
        max_relative_positions: -1,
        pad_token_id: 0,
        position_biased_input: true,
        pos_att_type: null,
    }
}


criterion: training.criterion.FocalLoss
criterion_params: {
    gamma: 3.5
}

optimizer: training.optimizer.Adam
lr: 0.000015
lr_alpha: 30
optimizer_params: {}

scheduler: training.scheduler.Scheduler
scheduler_params: {
  num_training_steps: 10000,
  scheduler_name: "get_cosine_with_hard_restarts_schedule_with_warmup"
}


n_epochs: 20

best_score: 0.23