name: "64"

seed: 823
data_path: "/home/jupyter/mnt/s3/rnd-shared/projects/yandex_cup_2023/ML/RecSys/input_data/"
n_splits: 3

batch_size: 90
max_len: 114

model: model.net.TransNetwork30
model_params: {
    cnn_params: {
      channels: [[768, 64], [64, 256], [256, 512], [512, 768]],
      activation: "leaky_relu",
      dropout: 0.02
    }
}


criterion: training.criterion.FocalLoss
criterion_params: {
    gamma: 0.8
}

optimizer: training.optimizer.Adam
lr: 0.000015
lr_alpha: 30
optimizer_params: {}

scheduler: training.scheduler.Scheduler
scheduler_params: {
  num_training_steps: 10000,
  scheduler_name: "get_cosine_with_hard_restarts_schedule_with_warmup"
}

use_cv: true
cv_n_epochs: 22
cv_min_score_to_save_predictions: 0.23

use_solo: true
solo_n_epochs: 20
solo_save_last_n_epochs: 2

dataset: data.dataset.TaggingDataset
collator: data.dataset.Collator

use_ema: true