name: "6"

seed: 11
data_path: "/home/jupyter/mnt/s3/rnd-shared/projects/yandex_cup_2023/ML/RecSys/input_data/"
n_splits: 3

batch_size: 64
max_len: 128

model: model.net.TransNetwork4
model_params: {
    input_dim: 768,
    hidden_dim: 512,
    encoder_cfg: {
        vocab_size: 1,
        hidden_size: 768,
        num_hidden_layers: 12,
        num_attention_heads: 12,
        intermediate_size: 3072,
        hidden_act: "gelu",
        hidden_dropout_prob: 0.001,
        attention_probs_dropout_prob: 0.001,
        max_position_embeddings: 128,
        type_vocab_size: 0,
        initializer_range: 0.02,
        layer_norm_eps: 0.0000001,
        relative_attention: false,
        max_relative_positions: -1,
        pad_token_id: 0,
        position_biased_input: true,
        pos_att_type: null,
    }
}


criterion: training.criterion.FocalLoss
criterion_params: {
    gamma: 0.8,
    class_weights: [2.3, 2.4, 3.3, 3.7, 4.6, 3.7, 3.5, 4.8, 4.8, 3.9, 4.9, 4.3, 4.3, 4.8, 5.3, 4.5, 5.2, 4.7, 5.0, 5.2, 5.4, 4.9, 5.3, 4.1, 5.3, 5.0, 5.2, 5.7, 4.6, 5.2, 5.4, 5.1, 5.1, 5.5, 5.9, 4.6, 6.0, 5.3, 5.6, 5.3, 5.4, 5.8, 5.9, 4.8, 5.5, 5.4, 5.6, 5.2, 5.8, 5.9, 5.4, 6.0, 5.8, 5.9, 5.5, 5.8, 5.9, 5.9, 5.6, 6.0, 5.7, 6.4, 5.6, 5.7, 5.4, 5.9, 6.0, 6.1, 5.8, 6.0, 5.6, 6.1, 6.0, 5.7, 5.7, 5.8, 5.9, 5.9, 6.1, 6.4, 6.1, 5.6, 5.9, 5.8, 6.0, 5.8, 5.9, 5.9, 6.1, 5.8, 6.0, 6.4, 5.8, 5.9, 6.2, 5.8, 5.7, 5.9, 6.0, 5.6, 6.2, 5.9, 5.9, 5.8, 6.2, 6.3, 6.4, 6.3, 6.1, 6.3, 6.2, 6.2, 5.7, 6.2, 6.3, 6.3, 6.1, 5.8, 6.0, 6.0, 6.4, 6.0, 6.0, 5.9, 6.2, 6.4, 6.4, 6.1, 6.5, 6.1, 6.5, 6.2, 6.5, 6.2, 6.1, 6.3, 6.8, 6.1, 6.1, 6.6, 6.6, 6.3, 6.4, 6.0, 6.2, 6.1, 6.3, 6.6, 6.7, 6.4, 6.3, 6.0, 6.7, 6.4, 6.4, 6.4, 6.7, 6.2, 6.2, 6.5, 6.3, 6.4, 6.4, 6.6, 6.3, 6.5, 6.7, 6.3, 6.3, 6.2, 6.4, 6.7, 6.3, 6.2, 6.3, 6.3, 6.6, 6.2, 6.2, 6.8, 6.4, 6.7, 6.5, 6.3, 6.8, 6.5, 6.4, 6.4, 6.7, 6.5, 6.6, 6.3, 6.3, 6.7, 6.7, 6.4, 6.5, 6.6, 6.4, 6.7, 6.8, 6.4, 6.5, 6.6, 6.4, 6.6, 6.5, 6.5, 6.7, 6.6, 6.7, 6.9, 6.6, 6.7, 6.5, 6.5, 6.7, 6.6, 6.5, 6.6, 6.6, 6.6, 6.8, 6.6, 6.6, 6.6, 6.8, 6.5, 6.5, 6.8, 6.7, 6.7, 6.6, 6.7, 6.5, 6.9, 6.7, 6.7, 6.9, 6.6, 6.7, 6.6, 6.8, 6.7, 6.6, 6.8, 6.6, 6.7, 6.8, 6.6, 6.8, 6.7, 6.6, 6.8, 6.8, 6.7]
}

optimizer: training.optimizer.Adam
lr: 0.000015
lr_alpha: 30
optimizer_params: {}

scheduler: training.scheduler.Scheduler
scheduler_params: {
  num_training_steps: 10000,
  scheduler_name: "get_cosine_with_hard_restarts_schedule_with_warmup"
}

use_cv: true
cv_n_epochs: 18
cv_min_score_to_save_predictions: 0.23

use_solo: true
solo_n_epochs: 13
solo_save_last_n_epochs: 3