seed: 11
data_path: "/Users/yaroslav.hnykov/Desktop/Study/VCS/YandexCUP2023/ML/RecSys/input_data/"
val_size: 0.1

batch_size: 64
max_len: 100

model: model.net.TransNetwork3
model_params: {}

criterion: training.criterion.BCEWithLogitsLoss

optimizer: training.optimizer.AdamW
optimizer_params: {
  lr: 0.00001
}

scheduler: training.scheduler.Scheduler
scheduler_params: {
  num_training_steps: 2500,
  scheduler_name: "get_linear_schedule_with_warmup"
}


n_epochs: 10

best_score: 0.25